---
title: Cognopia
timezone: UTC
collections:
  posts:
  default:
   name:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  includes:
    title: includes
    output: true
description: 
baseurl: ''
url: ''
paginate: 4
paginate_path: "/news/page:num/"
markdown: kramdown
theme: minima
gems:
- jekyll-paginate
exclude:
- Gemfile
- Gemfile.lock
